title: My Jekyll Blog
description: A simple and clean blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://YOUR_USERNAME.github.io" # the base hostname & protocol for your site
github_username: YOUR_USERNAME

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed